<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateUserDevicesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('user_devices', function (Blueprint $table) {
            $table->id();
            $table->foreignId('user_id')->constrained();
            $table->string('platform')->nullable();
            $table->string('package')->nullable();
            $table->string('package_version')->nullable();
            $table->integer('screen_width')->nullable();
            $table->integer('screen_height')->nullable();
            $table
                ->string('device_model')
                ->nullable()
                ->comment('デバイスのモデル');
            $table
                ->string('device_name')
                ->nullable()
                ->comment('デバイス名');
            $table
                ->string('device_type')
                ->nullable()
                ->comment('デバイスのタイプ');
            $table
                ->string('graphics_device_id')
                ->nullable()
                ->comment('グラフィックデバイスの識別コード');
            $table
                ->string('graphics_device_name')
                ->nullable()
                ->comment('グラフィックデバイス名');
            $table
                ->string('graphics_device_type')
                ->nullable()
                ->comment('グラフィックデバイスのタイプ');
            $table
                ->string('graphics_device_vendor')
                ->nullable()
                ->comment('グラフィックデバイスのベンダー');
            $table
                ->string('graphics_device_vendor_id')
                ->nullable()
                ->comment('グラフィックデバイスのベンダーの識別コード');
            $table
                ->string('graphics_device_version')
                ->nullable()
                ->comment('グラフィックデバイスのAPIとバージョン');
            $table
                ->integer('graphics_memory_size')
                ->nullable()
                ->comment('ビデオメモリ');
            $table
                ->boolean('graphics_multi_threaded')
                ->nullable()
                ->comment(
                    'グラフィックデバイスがマルチスレッドレンダリングを行うか？'
                );
            $table
                ->integer('graphics_shader_level')
                ->nullable()
                ->comment('グラフィックデバイスのシェーダーの性能レベル');
            $table
                ->integer('max_texture_size')
                ->nullable()
                ->comment('テクスチャの最大サイズ');
            $table
                ->integer('npot_support')
                ->nullable()
                ->comment('対応しているNPOTテクスチャ');
            $table
                ->string('operating_system')
                ->nullable()
                ->comment('OSとバージョン');
            $table
                ->integer('processor_count')
                ->nullable()
                ->comment('プロセッサーの数');
            $table
                ->integer('processor_frequency')
                ->nullable()
                ->comment('プロセッサーの周波数');
            $table
                ->string('processor_type')
                ->nullable()
                ->comment('プロセッサー名');
            $table
                ->integer('supported_render_target_count')
                ->nullable()
                ->comment('レンダリングターゲットの数');
            $table
                ->boolean('supports_2darray_textures')
                ->nullable()
                ->comment('2D配列テクスチャに対応しているか？');
            $table
                ->boolean('supports_3dtextures')
                ->nullable()
                ->comment('3Dテクスチャに対応しているか？');
            $table
                ->boolean('supports_accelerometer')
                ->nullable()
                ->comment('加速度センサーに対応しているか？');
            $table
                ->boolean('supports_audio')
                ->nullable()
                ->comment('オーディオに対応しているか？');
            $table
                ->boolean('supports_compute_shaders')
                ->nullable()
                ->comment('ComputeShaderに対応しているか？');
            $table
                ->boolean('supports_gyroscope')
                ->nullable()
                ->comment('ジャイロスコープに対応しているか？');
            $table
                ->boolean('supports_image_effects')
                ->nullable()
                ->comment('イメージエフェクトに対応しているか？');
            $table
                ->boolean('supports_instancing')
                ->nullable()
                ->comment('GPUドローコールのインスタンス化に対応しているか？');
            $table
                ->boolean('supports_location_service')
                ->nullable()
                ->comment('GPSに対応しているか？');
            $table
                ->boolean('supports_motion_vectors')
                ->nullable()
                ->comment('モーションベクターに対応しているか？');
            $table
                ->boolean('supports_raw_shadow_depth_sampling')
                ->nullable()
                ->comment('シャドウマップからのサンプリングは生のデプスか？');
            $table
                ->boolean('supports_render_textures')
                ->nullable()
                ->comment('レンダリングテクスチャに対応しているか？');
            $table
                ->boolean('supports_render_to_cubemap')
                ->nullable()
                ->comment(
                    'キューブマップに対するレンダリングに対応しているか？'
                );
            $table
                ->boolean('supports_shadows')
                ->nullable()
                ->comment('影に対応しているか？');
            $table
                ->boolean('supports_sparse_textures')
                ->nullable()
                ->comment('スパーステクスチャに対応しているか？');
            $table
                ->boolean('supports_stencil')
                ->nullable()
                ->comment('ステンシルバッファに対応しているか？');
            $table
                ->boolean('supports_vibration')
                ->nullable()
                ->comment('バイブレーションに対応しているか？');
            $table
                ->integer('system_memory_size')
                ->nullable()
                ->comment('システムメモリ');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('user_devices');
    }
}
